runtime: python311 # or another supported version
#manual_scaling:
  #instances: 1
  
entrypoint: gunicorn -b :$PORT flask_app:app

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

  url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto